version: "1.0"
services:
  eureka-server:
    container_name: eureka_server
    build: ./movie-services-registry
    ports:
      - "8761:8761"
    environment:
      - server.port=8761
      - spring.application.name=movie-services-registry
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
  booking-service:
    build: ./movie-services-registry
    container_name: booking-service
    ports:
      - "8080:8080"
    environment:
      - spring.application.name=booking-service
      - server.port=8761
      - eureka.client.register-with-eureka=true
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "9090:9090"
    environment:
      - spring.application.name=payment-service
      - server.port=9090
      - eureka.client.register-with-eureka=true
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "7070:7070"
    environment:
      - spring.application.name=notification-service
      - server.port=7070
      - eureka.client.register-with-eureka=true
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/



