version: "1.0"
services:
  eureka-server:
    container_name: eureka_server
    build: ./movie-services-registry
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - APPLICATION_NAME=movie-services-registry
      - REGISTER_WITH_EUREKA=false
      - FETCH_REGISTRY=false
  booking-service:
    build: ./movie-services-registry
    container_name: booking-service
    ports:
      - "8080:8080"
    environment:
      - APPLICATION_NAME=booking-service
      - SERVER_PORT=8761
      - REGISTER_WITH_EUREKA=true
      - DEFAULT_ZONE=http://eureka-server:8761/eureka/
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8081:8081"
    environment:
      - APPLICATION_NAME=payment-service
        SERVER_PORT=9090
      - REGISTER_WITH_EUREKA=true
      - DEFAULT_ZONE=http://eureka-server:8761/eureka/
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "7070:7070"
    environment:
      - APPLICATION_NAME=notification-service
      - SERVER_PORT=7070
      - REGISTER_WITH_EUREKA=true
      - DEFAULT_ZONE=http://eureka-server:8761/eureka/
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8765:8765"
    environment:
      - APPLICATION_NAME=api-gateway
      - SERVER_PORT=8765
      - REGISTER_WITH_EUREKA=true
      - DEFAULT_ZONE=http://eureka-server:8761/eureka/



